// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['app']['App']['Bootstrap']();
}

export function CancelLoadTest(arg1) {
  return window['go']['app']['App']['CancelLoadTest'](arg1);
}

export function CancelRequest(arg1) {
  return window['go']['app']['App']['CancelRequest'](arg1);
}

export function ClearHistory(arg1) {
  return window['go']['app']['App']['ClearHistory'](arg1);
}

export function ClearLoadTests(arg1) {
  return window['go']['app']['App']['ClearLoadTests'](arg1);
}

export function DeleteEntity(arg1, arg2) {
  return window['go']['app']['App']['DeleteEntity'](arg1, arg2);
}

export function DuplicateRequest(arg1) {
  return window['go']['app']['App']['DuplicateRequest'](arg1);
}

export function ExecuteRequest(arg1) {
  return window['go']['app']['App']['ExecuteRequest'](arg1);
}

export function ExportCurl(arg1) {
  return window['go']['app']['App']['ExportCurl'](arg1);
}

export function GetOAuthToken(arg1) {
  return window['go']['app']['App']['GetOAuthToken'](arg1);
}

export function ImportCurl(arg1, arg2) {
  return window['go']['app']['App']['ImportCurl'](arg1, arg2);
}

export function ImportWSDL(arg1) {
  return window['go']['app']['App']['ImportWSDL'](arg1);
}

export function MoveFolder(arg1) {
  return window['go']['app']['App']['MoveFolder'](arg1);
}

export function NewRequest(arg1, arg2) {
  return window['go']['app']['App']['NewRequest'](arg1, arg2);
}

export function PickFile(arg1) {
  return window['go']['app']['App']['PickFile'](arg1);
}

export function RunFlow(arg1) {
  return window['go']['app']['App']['RunFlow'](arg1);
}

export function RunLoadTest(arg1) {
  return window['go']['app']['App']['RunLoadTest'](arg1);
}

export function SaveCollection(arg1) {
  return window['go']['app']['App']['SaveCollection'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['app']['App']['SaveEnvironment'](arg1);
}

export function SaveFlow(arg1) {
  return window['go']['app']['App']['SaveFlow'](arg1);
}

export function SaveFolder(arg1) {
  return window['go']['app']['App']['SaveFolder'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['app']['App']['SaveRequest'](arg1);
}

export function SaveResponse(arg1) {
  return window['go']['app']['App']['SaveResponse'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SaveTabs(arg1) {
  return window['go']['app']['App']['SaveTabs'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['app']['App']['SaveWorkspace'](arg1);
}

export function WindowClose() {
  return window['go']['app']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['app']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['app']['App']['WindowToggleMaximise']();
}
