// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Bootstrap():Promise<models.AppState>;

export function CancelLoadTest(arg1:string):Promise<boolean>;

export function CancelRequest(arg1:string):Promise<boolean>;

export function ClearHistory(arg1:string):Promise<void>;

export function ClearLoadTests(arg1:string):Promise<void>;

export function DeleteEntity(arg1:string,arg2:string):Promise<void>;

export function DuplicateRequest(arg1:models.RequestDefinition):Promise<models.RequestDefinition>;

export function ExecuteRequest(arg1:models.ExecuteRequestInput):Promise<models.ExecuteRequestResult>;

export function ExportCurl(arg1:models.RequestDefinition):Promise<string>;

export function GetOAuthToken(arg1:models.OAuthTokenInput):Promise<models.OAuthTokenResult>;

export function ImportCurl(arg1:string,arg2:string):Promise<models.RequestDefinition>;

export function ImportWSDL(arg1:models.WSDLImportInput):Promise<models.WSDLImportResult>;

export function MoveFolder(arg1:models.MoveFolderInput):Promise<void>;

export function NewRequest(arg1:string,arg2:string):Promise<models.RequestDefinition>;

export function PickFile(arg1:string):Promise<string>;

export function RunFlow(arg1:models.FlowRunInput):Promise<models.FlowRunResult>;

export function RunLoadTest(arg1:models.LoadTestInput):Promise<models.LoadTestRun>;

export function SaveCollection(arg1:models.Collection):Promise<models.Collection>;

export function SaveEnvironment(arg1:models.Environment):Promise<models.Environment>;

export function SaveFlow(arg1:models.Flow):Promise<models.Flow>;

export function SaveFolder(arg1:models.Folder):Promise<models.Folder>;

export function SaveRequest(arg1:models.RequestDefinition):Promise<models.RequestDefinition>;

export function SaveResponse(arg1:models.ExecuteRequestResult):Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SaveTabs(arg1:Array<string>):Promise<void>;

export function SaveWorkspace(arg1:models.Workspace):Promise<models.Workspace>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
